- name: EPEL installed
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  become: yes

- name: required packages installed
  yum:
    name:
      - python34-pip
      - git
      - sudo
  become: yes
