---
- name: pip_dependencies
  pip:
    requirements: "{{ backend_requirements }}"
    executable: pip3
    state: latest
    extra_args: --user
  become_user: "{{ backend_user }}"
  become: yes

- name: backend_service_restarted
  systemd:
    name: "{{ backend_service_name }}"
    daemon-reload: yes
    state: restarted
  become: yes
